<?php

use Drupal\Core\Cache\Cache;  
use Drupal\node\NodeInterface;

/**
 * Implements hook_node_presave().
 */
function latest_artist_node_presave(NodeInterface $node) {
  latest_artist_invalidate_node($node);
}

/**
 * Implements hook_node_presave().
 */
function latest_artist_node_delete(NodeInterface $node) {
  latest_artist_invalidate_node($node);
}

/**
 * Invalidate custom cache associated to artists node.
 */
function latest_artist_invalidate_node(NodeInterface $node) {  
  if ($node->getType() == 'artists') {
  //$tags = ['node_list'];
  $tags =['latest_artist_updates'];
  Cache::invalidateTags($tags);
  }
}